DROP DATABASE IF EXISTS elections;
CREATE DATABASE elections;
USE elections;

CREATE TABLE voters (
id INT NOT NULL AUTO_INCREMENT,
firstName VARCHAR(20) NOT NULL,
lastName VARCHAR(20) NOT NULL,
patronymic VARCHAR(20) NULL,
street VARCHAR(30) NOT NULL,
house VARCHAR(7) NOT NULL,
apartment INT NULL,
login VARCHAR (20) NOT NULL UNIQUE,
voter_password VARCHAR(20) NOT NULL,
token VARCHAR(36) NULL,
PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE proposals (
id INT NOT NULL AUTO_INCREMENT,
voter_id INT NULL,
proposalTitle VARCHAR(100) NOT NULL UNIQUE,
PRIMARY KEY(id),
FOREIGN KEY (voter_id) REFERENCES voters (id) ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE candidates (
id INT NOT NULL AUTO_INCREMENT,
voter_id INT NOT NULL UNIQUE,
agree TINYINT NOT NULL DEFAULT FALSE,
PRIMARY KEY(id),
FOREIGN KEY(voter_id) REFERENCES voters(id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE programmes (
id INT NOT NULL AUTO_INCREMENT,
candidate_id INT NOT NULL UNIQUE,
PRIMARY KEY(id),
FOREIGN KEY(candidate_id) REFERENCES candidates(id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE programme_proposals (
id INT NOT NULL AUTO_INCREMENT,
proposal_id INT NOT NULL,
programme_id INT NOT NULL,
PRIMARY KEY(id),
UNIQUE KEY programme_proposals(proposal_id, programme_id),
FOREIGN KEY (proposal_id) REFERENCES proposals (id) ON DELETE CASCADE,
FOREIGN KEY (programme_id) REFERENCES programmes (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE ratings (
id INT NOT NULL AUTO_INCREMENT,
voter_id INT NOT NULL,
rating INT NOT NULL DEFAULT 5,
proposal_id INT NOT NULL,
UNIQUE KEY token_proposalId (voter_id, proposal_id),
PRIMARY KEY(id),
FOREIGN KEY (voter_id) REFERENCES voters (id) ON DELETE CASCADE,
FOREIGN KEY (proposal_id) REFERENCES proposals (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE elections (
id INT NOT NULL AUTO_INCREMENT,
started TINYINT NOT NULL DEFAULT FALSE,
finished TINYINT NOT NULL DEFAULT FALSE,
PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE votes (
id INT NOT NULL AUTO_INCREMENT,
voter_id INT NOT NULL UNIQUE,
candidate_id INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (voter_id) REFERENCES voters (id) ON DELETE CASCADE,
FOREIGN KEY (candidate_id) REFERENCES candidates (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE against_all (
id INT NOT NULL AUTO_INCREMENT,
voter_id INT NOT NULL UNIQUE,
PRIMARY KEY(id),
FOREIGN KEY (voter_id) REFERENCES voters (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;
