DROP DATABASE IF EXISTS ttschool;
CREATE DATABASE `ttschool`;
USE `ttschool`;

CREATE TABLE school (
id INT NOT NULL AUTO_INCREMENT,
school_name VARCHAR(20) NOT NULL,
year_of_study INT NOT NULL,
UNIQUE KEY school_name_year (school_name, year_of_study),
PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE school_group (
id INT NOT NULL AUTO_INCREMENT,
school_id INT NOT NULL,
group_name VARCHAR(20) NOT NULL,
room VARCHAR(5) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(school_id) REFERENCES school (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE trainee (
id INT NOT NULL AUTO_INCREMENT,
group_id INT NULL,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
rating INT NULL,
PRIMARY KEY(id),
FOREIGN KEY(group_id) REFERENCES school_group (id) ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE subj (
id INT NOT NULL AUTO_INCREMENT,
subject_name VARCHAR(20) NOT NULL UNIQUE,
PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE group_subject (
id INT NOT NULL AUTO_INCREMENT,
group_id INT NOT NULL,
subject_id INT NOT NULL,
UNIQUE KEY group_subject (group_id, subject_id),
PRIMARY KEY(id),
FOREIGN KEY(group_id) REFERENCES school_group (id) ON DELETE CASCADE,
FOREIGN KEY(subject_id) REFERENCES subj (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;